void code220(int sock, bool verbose);
void code250(int sock, bool verbose, const char *message);
void code221(int sock, bool verbose);
void code421(int sock, bool verbose);
void code250(int sock, bool verbose);
void code354(int sock, bool verbose);
void code500(int sock, bool verbose);
void code500(int sock, bool verbose, const char *message);
void code501(int sock, bool verbose);
void code501(int sock, bool verbose, const char *message);
void code503(int sock, bool verbose);
void code503(int sock, bool verbose, const char *message);
void code550(int sock, bool verbose);
void code550(int sock, bool verbose, const char *message);