name: Build and Push KVS Docker Image

on:
    push:
        branches:
            - workflow
            - kvs

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install C++ and CMake
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential cmake

            - name: Install gRPC
              uses: hindicator/grpc-setup@v1
              with:
                grpc-version: 1.62.0
                
            - name: Build the project
              run: |
                cd kvs && pwd
                mkdir -p build
                cd build 
                pwd
                cmake -DCMAKE_PREFIX_PATH="$GRPC_ROOT" ..
                make -j$(nproc)
                cd ..
                pwd

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3      
              
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: "langqin"
                password: "Ql110119!"

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: ./kvs
                file: ./kvs/Dockerfile
                platforms: linux/amd64
                push: true
                tags: langqin/kvs:latest
